name: dsbroker
version: 1.1.5
description: DSA Broker which manages connections of DSLinks
authors:
- Rick Zhou <rinick@gmail.com>
- Kenneth Endfinger <k.endfinger@dglogik.com>
- Matthew Butler <butler.matthew@gmail.com>
homepage: https://get.iot-dsa.org
dependencies:
  uuid: 1.0.1
  dslink: ^1.0.3
environment:
  sdk: ">=1.13.0 <2.0.0"
executables:
  dsbroker: broker
